config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
 
  get 'about' , to: 'pages#about'
  get 'contact', to: 'pages#contact'

  root to: 'pages#home'
end

app/models/blog.rb
class Blog < ApplicationRecord
    enum status: { draft: 0, published: 1}
    extend FriendlyId
    friendly_id :title, use: :slugged

    validates_presence_of :title, :body

    belongs_to :topic

    def self.special_blogs
        all
    end

    def self.featured_blog
        limit(2)
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.page(params[:page]).per(5)
    @page_title = "Blog"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blogs_url, notice: 'Blog was successfully created.' }   
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    
    redirect_to blogs_url, notice: 'Blog post has been successfully updated.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.haml
.blog-post
    %h2.blog-post-title
        = link_to blog.title, blog
    %p.blog-post-meta
        = distance_of_time_in_words(blog.created_at, Time.now) + " ago"
    -if logged_in?(:site_admin)
        %p.blog-post-meta
            = link_to blog.status, toggle_status_blog_path(blog) 
            |
            = link_to 'Edit', edit_blog_path(blog)
            |
            = link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }
    = blog.body

app/views/blogs/_form.html.haml
=form_for(@blog) do |f| 
    -if @blog.errors.any? 
        #error_explanation
            %h2= "#{pluralize(@blog.errors.count, "error")}  prohibited this blog from being saved:"

    %ul
    -@blog.errors.full_messages.each do |message|
        %li= @message

    .form-group
    = f.label :title 
    = f.text_field :title, class: 'form-control' 

    .form-group
    = f.label :body 
    = f.text_area :body, rows: 15, class: 'form-control'

    .form-group
    = f.submit "Submit", class: 'btn btn-primary'

app/views/blogs/edit.html.haml
.col-sm-8.blog-main
    
    %h1 Editing Blog

    =render 'form', blog: @blog 

    =link_to 'Show', @blog  
    |
    =link_to 'Back', blogs_path 

app/views/blogs/index.html.haml
.col-sm-8.blog-main
  =paginate @blogs
  
  =render @blogs 
  
  =paginate @blogs

app/views/blogs/new.html.haml
.col-sm-8.blog-main
    
    %h1 New Blog

    =render 'form', blog: @blog 
    =link_to 'Back', blogs_path 

app/views/blogs/show.html.haml
.col-sm-8.blog-main
  %h2
    = @blog.title

  = link_to 'Edit', edit_blog_path(@blog) if logged_in?(:site_admin)
  
  %p
    = @blog.body 