config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
 
  get 'about' , to: 'pages#about'
  get 'contact', to: 'pages#contact'

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :technologies
    accepts_nested_attributes_for :technologies, 
                                   reject_if: lambda{ |attrs| attrs['name'].blank? }

    validates_presence_of :title, :body

    mount_uploader :thumb_image, PortfolioUploader
    mount_uploader :main_image, PortfolioUploader

    def self.angular
        where(subtitle: 'Angular')
    end

    def self.by_position
        order(position: :ASC)
    end

    scope :ruby_on_rails_portfolio_items, -> {where(subtitle: 'Ruby o Rails')}
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]
    access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all
    layout 'portfolio'

    def index
        @portfolio_items = Portfolio.by_position
    end

    def sort
        params[:order].each do |key, value|
            Portfolio.find(value[:id]).update(position: value[:position])
        end

        render nothing: true
    end

    def show
    end

    def new
        @portfolio_item = Portfolio.new
        3.times {@portfolio_item.technologies.build}
    end

    def create
        @portfolio_item = Portfolio.new(portfolio_params)

        respond_to do |format|
            if @portfolio_item.save
                format.html { redirect_to portfolios_path, notice: 'Your portfolio has been created'}
            else
                format.html {render :new}
            end
        end 
    end

    def edit
    end

    def update
        respond_to do |format|
            if @portfolio_item.update(portfolio_params)
                format.html { redirect_to portfolios_path, notice: 'Your portfolio succesfully updated'}
            else
                format.html {render :edit}
            end
        end 
    end

    def destroy
        @portfolio_item.destroy

        respond_to do |format|
            format.html { redirect_to portfolios_path, notice: "Portfolio item deleted"}
        end
    end

    private def portfolio_params
        params.require(:portfolio).permit(  :title, 
                                            :subtitle, 
                                            :body,
                                            :main_image,
                                            :thumb_image, 
                                            technologies_attributes: [:name])
    end

    def set_portfolio_item
        @portfolio_item = Portfolio.find(params[:id])
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper

    def image_generator(height:,width:)
        "https://via.placeholder.com/#{height}x#{width}"
    end

    def portfolio_img img, type
        if img.model.main_image? || img.model.thumb_image?
            img.to_s
        elsif type == 'thumb'
            image_generator(height: '350', width: '200')
        elsif type == 'main'
            image_generator(height: '600', width: '400')
        end
    end
end

app/views/portfolios/_form.html.haml
=form_for(@portfolio_item) do |f|
    .row
        .col-md-6
            .form-group
                = f.label :title 
                = f.text_field :title, class: 'form-control'

            .form-group
                = f.label :subtitle 
                = f.text_field :subtitle, class: 'form-control'

            .form-group
                %label.btn.btn-primary
                    Upload a main image file #{f.file_field :main_image, style: 'display:none;'}

            .form-group
                %label.btn.btn-primary
                    Upload a thumb image file #{f.file_field :thumb_image, style: 'display:none;'}
        .col-md-6
            .form-group
                = f.label :body 
                = f.text_area :body, class: 'form-control', rows: 13

        
        .col-md-12
            %hr
            %h3 Technologies used: 

            %div
                =f.fields_for :technologies do |technology_form|
                    %div.form-group
                        = technology_form.label :name
                        = technology_form.text_field :name, class: 'form-control'

            .form-group
            = f.submit "Save Portfolio Item", class: 'btn btn-primary btn-block'

app/views/portfolios/_portfolio_item.html.haml
.card{"data-id" => portfolio_item.id}
    =image_tag portfolio_img(portfolio_item.thumb_image,'thumb'), width: '100%'
    %p.card-text
        %span
            =link_to portfolio_item.title, portfolio_show_path(portfolio_item)
        %p= portfolio_item.subtitle

app/views/portfolios/edit.html.haml
.container.portfolio-container
    %h1 Edit Portfolio Item

    = render 'form', portfolio_item: @portfolio_item

app/views/portfolios/index.html.haml
=link_to "Create New Item" , new_portfolio_path if logged_in?(:site_admin)

.album.text-muted
    .container
        %div{:class => "row #{"sortable" if logged_in?(:site_admin)}"}
            =render partial: 'portfolio_item', collection: @portfolio_items

app/views/portfolios/new.html.haml
.container.portfolio-container
 
    %h1 New Portfolio Item

    = render 'form', portfolio_item: @portfolio_item

app/views/portfolios/show.html.haml
.container.portfolio-container
    .row
        .col-md-7
            = image_tag portfolio_img(@portfolio_item.main_image, 'main'),width: '100%'
        .col-md-5
            %h1= @portfolio_item.title
            %hr
            %em= @portfolio_item.subtitle
            %p= @portfolio_item.body
            %hr

            %h3 Technologies used
            -@portfolio_item.technologies.each do |t|
                %p= t.name