config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
 
  get 'about' , to: 'pages#about'
  get 'contact', to: 'pages#contact'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.haml
.mastfoot
    .inner
        %p.app-footer 
            = copyright_generator

app/views/shared/_application_nav.html.haml
.masthead.clearfix
    .inner
        %h3.masthead-brand Michał Urban
        %nav.nav.nav-masthead.app-nav
            =nav_helper 'nav-link', 'span'
            =login_helper('nav-link')

app/views/shared/_blog_footer.html.haml
%footer.blog-footer
    %p
        =copyright_generator
    %p
        %a{:href => "#"} Back to top

app/views/shared/_blog_masthead.html.haml
.blog-header
    .container
        .h1.blog-title My Blog
        %p.lead.blog-description An example blog
        = link_to 'Write a new blog', new_blog_path if logged_in?(:site_admin)

app/views/shared/_blog_nav.html.haml
.blog-masthead
    .container
        %nav.nav.blog-nav
            =nav_helper 'nav-link', 'span'
            =login_helper('nav-link')

app/views/shared/_blog_sidebar.html.haml
.col-sm-3.offset-sm-1.blog-sidebar
    .sidebar-module.sidebar-module-inset
        %h4 About
        %p
            Etiam porta
            %em sem malesuada magna
            mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.

    .sidebar-module
    %h4 Elsewhere

    %ol.list-unstyled.social-links
        %li
            =link_to "https://github.com" do
                =fa_icon "github"
        %li
            =link_to "https://instagram.com" do
                =fa_icon "instagram"
        %li
            =link_to "https://facebook.com" do
                =fa_icon "facebook"
        %li
            =link_to "https://twitter.com" do
                =fa_icon "twitter"

app/views/shared/_nav.html.haml
%div{class: "#{location}" }
    %div
    =link_to "Home", root_path
    %div
    =link_to "About", about_path
    %div
    =link_to "Contact", contact_path
    %div
    =link_to "Blog", blogs_path
    %div
    =link_to "Portfolio", portfolios_path

app/views/shared/_portfolio_footer.html.haml
%footer.text-muted
    .container
        %p.float-right
            %a{:href => "#"} Back to top
            | 
            =link_to 'View all portfolio Items', portfolios_path
        %p= copyright_generator
            
        

app/views/shared/_portfolio_masthead.html.haml
%section.jumbotron.text-center
    .container
        %h1.jumbotron-heading Album example
        %p.lead.text-muted Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.
        %p
            =link_to 'About me', about_path, class: 'btn btn-primary'
            =link_to 'My blog', blogs_path, class: 'btn btn-secondary'

app/views/shared/_portfolio_nav.html.haml
#navbarHeader.collapse.bg-dark
    .container
        .row
            .col-sm-8.py-4
                %h4.text-white About
                %p.text-muted Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.
            .col-sm-4.py-4
                %h4.text-white Explore
                %ul.list-unstyled
                    =nav_helper 'text-white', 'li'
                    %li= login_helper('text-white')
.navbar.navbar-dark.bg-dark
    .container.d-flex.justify-content-between
        %a.navbar-brand{:href => "#"} Michał Urban
        %button.navbar-toggler{"aria-controls" => "navbarHeader", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarHeader", "data-toggle" => "collapse", :type => "button"}
            %span.navbar-toggler-icon